let actualBankNames = [
    "State Bank of India",
    "Bank of Baroda",
    "IDBI Bank",
    "Union Bank of India",
    "punjab national bank",
    "IndusInd Bank",
    "ICICI Bank",
    "HDFC Bank",
    "Axis Bank",
    "Kotak Mahindra Bank",
    "Central Bank of India",
    "Bank of India",
    "Yes Bank Limited",
    "Canara Bank",
    "Indian Overseas Bank",
    "Indian Bank",
    "UCO Bank",
    "Bank of Maharashtra",
    "Bandhan Bank",
    "Federal Bank",
    "DCB Bank",
    "Dhanlaxmi Bank",
    "Equitas Small Finance Bank",
    "Utkarsh Small Finance Bank Ltd",
    "Sonali Bank",
    "Punjab & Sind Bank",
    "Karnataka Bank",
    "Jammu & Kashmir Bank",
    "South Indian Bank"
]
module.exports = {actualBankNames}